const { chromium } = require('playwright')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

async function main() {
  const output = path.resolve(process.argv[2] || '.test-output/rehearsal')
  fs.mkdirSync(output, { recursive: true })
  const browser = await chromium.launch({ channel: process.env.VELA_BROWSER_CHANNEL || undefined, headless: true })
  const page = await browser.newPage({ viewport: { width: 1200, height: 950 } })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  const base = process.env.VELA_TEST_URL || 'http://127.0.0.1:5198/tests/rehearsal/index.html'
  const checks = []
  const wait = async locator => { await locator.waitFor({ state: 'visible' }) }
  const open = async () => { await page.getByRole('button', { name: '剧情试演', exact: true }).click(); await wait(page.getByRole('dialog')) }
  const generate = async () => {
    await page.getByLabel('创作意图', { exact: true }).fill('师父真实背叛主角，但读者最终能理解。')
    await page.getByLabel('必须保留的约束', { exact: true }).fill('主角不轻易原谅；对手不降智。')
    await page.getByRole('button', { name: '试演三个方向', exact: true }).click()
  }
  try {
    await page.goto(base)
    await open()
    await generate()
    await wait(page.getByRole('button', { name: /2\. 掩盖旧案/ }))
    await page.getByRole('button', { name: /2\. 掩盖旧案/ }).click()
    await page.getByLabel('场景与信息揭示', { exact: true }).fill('从主角视角，只露线索。')
    await page.getByRole('button', { name: '试写短场景', exact: true }).click()
    await wait(page.getByRole('textbox', { name: '试写片段 · 可编辑', exact: true }))
    assert.match(await page.getByRole('textbox', { name: '试写片段 · 可编辑', exact: true }).inputValue(), /掩盖旧案/)
    await page.getByRole('textbox', { name: '试写片段 · 可编辑', exact: true }).fill('作者修改过的试写片段。')
    await page.getByRole('button', { name: /1\. 救下人证/ }).click()
    assert.equal(await page.getByRole('textbox', { name: '试写片段 · 可编辑', exact: true }).count(), 0)
    await page.getByRole('button', { name: /2\. 掩盖旧案/ }).click()
    assert.equal(await page.getByRole('textbox', { name: '试写片段 · 可编辑', exact: true }).inputValue(), '作者修改过的试写片段。')
    checks.push('生成三方向、选定方向试写、分方向保留作者编辑')
    await page.screenshot({ path: path.join(output, 'rehearsal-app-light.png') })

    await page.getByRole('button', { name: '追加到作者指导', exact: true }).click()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    const beforeSave = await page.evaluate(() => window.rehearsalTest.calls.filter(c => c.channel.startsWith('db:blueprint-upsert')))
    assert.equal(beforeSave.length, 0)
    await page.evaluate(() => { window.rehearsalTest.failSave = true })
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await wait(page.getByText(/蓝图保存失败/))
    await wait(page.getByText('● 未保存', { exact: true }))
    await page.evaluate(() => { window.rehearsalTest.failSave = false })
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await page.getByText('● 未保存', { exact: true }).waitFor({ state: 'hidden' })
    const saved = await page.evaluate(() => window.rehearsalTest.saved.get('A')[0])
    assert.match(saved.userGuidance, /^原有指导：保留雨夜。/)
    assert.match(saved.userGuidance, /掩盖旧案/)
    assert.doesNotMatch(saved.userGuidance, /作者修改过的试写片段/)
    assert.equal(saved.notes, '原有要点不变')
    assert.equal(saved.keyEvents, '师父交出行踪')
    checks.push('采用只追加作者指导；保存失败保留未保存状态；保存成功保留原有字段')

    await page.goto(base)
    await open()
    await page.evaluate(() => { window.rehearsalTest.mode = 'delayed' })
    await generate()
    await page.getByRole('button', { name: '取消生成', exact: true }).click()
    await page.waitForTimeout(2000)
    assert.equal(await page.getByRole('button', { name: /1\. 救下人证/ }).count(), 0)
    const cancellations = await page.evaluate(() => window.rehearsalTest.calls.filter(c => c.channel === 'llm:cancel').length)
    assert.ok(cancellations > 0)
    checks.push('取消请求后迟到结果不进入界面')
    await page.getByRole('button', { name: '试演三个方向', exact: true }).click()
    await page.evaluate(() => window.rehearsalTest.switchProject('B'))
    await wait(page.getByText('B 项目章节', { exact: true }))
    await page.waitForTimeout(2000)
    assert.equal(await page.getByRole('dialog').count(), 0)
    assert.equal(await page.evaluate(() => window.rehearsalTest.saved.get('B')[0].userGuidance), 'B 原有指导')
    checks.push('生成中切换项目会停止请求，结果不进入另一项目')

    await page.goto(base)
    await open()
    await generate()
    await wait(page.getByRole('button', { name: /1\. 救下人证/ }))
    await page.evaluate(() => { window.rehearsalTest.mode = 'malformed' })
    await page.getByRole('button', { name: '1. 设定意图', exact: true }).click()
    await page.getByRole('button', { name: '重新试演', exact: true }).click()
    await wait(page.getByRole('alert'))
    assert.match(await page.getByRole('alert').textContent(), /格式不符/)
    await page.getByRole('button', { name: '2. 比较方向', exact: true }).click()
    assert.equal(await page.getByRole('button', { name: /1\. 救下人证/ }).count(), 1)
    checks.push('格式错误明确报错，保留已有成功结果')

    for (const theme of ['light', 'dark']) {
      await page.goto(`${base}?theme=${theme}`)
      await page.setViewportSize({ width: 736, height: 900 })
      await open()
      await generate()
      await wait(page.getByRole('button', { name: /1\. 救下人证/ }))
      const bounds = await page.getByRole('dialog').evaluate(el => ({ width: el.clientWidth, scroll: el.scrollWidth }))
      assert.ok(bounds.scroll <= bounds.width, JSON.stringify(bounds))
      await page.screenshot({ path: path.join(output, `rehearsal-app-736-${theme}.png`) })
      await page.setViewportSize({ width: 390, height: 844 })
      const mobile = await page.getByRole('dialog').evaluate(el => ({ width: el.clientWidth, scroll: el.scrollWidth }))
      assert.ok(mobile.scroll <= mobile.width, JSON.stringify(mobile))
      await page.screenshot({ path: path.join(output, `rehearsal-app-390-${theme}.png`) })
    }
    checks.push('明暗主题与窄窗口下试演对话框无水平溢出')

    await page.goto(base)
    await page.evaluate(() => window.rehearsalTest.noModels())
    await open()
    await page.getByLabel('创作意图', { exact: true }).fill('测试')
    assert.equal(await page.getByRole('button', { name: '试演三个方向', exact: true }).isEnabled(), false)
    checks.push('没有生成模型时提示配置并禁用生成')
    assert.deepEqual(errors, [])
    fs.writeFileSync(path.join(output, 'rehearsal-ui-results.json'), JSON.stringify({ checks, errors }, null, 2))
    process.stdout.write(JSON.stringify({ checks, errors }, null, 2))
  } finally { await browser.close() }
}
main().catch(error => { process.stderr.write(String(error.stack || error)); process.exitCode = 1 })
