/* eslint-env node */
/* eslint-disable @typescript-eslint/no-require-imports -- Standalone CommonJS browser test runner. */
const { chromium } = require('playwright')
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict')
async function main() {
  const output = path.resolve(process.argv[2] || '.test-output/onboarding')
  fs.mkdirSync(output, { recursive: true })
  const browser = await chromium.launch({ channel: process.env.VELA_BROWSER_CHANNEL || undefined, headless: true })
  const page = await browser.newPage({ viewport: { width: 1200, height: 900 } })
  const base = process.env.VELA_TEST_URL || 'http://127.0.0.1:5198/tests/onboarding/index.html'
  const errors = [], checks = []
  page.on('pageerror', error => errors.push(error.message))
  const dialog = page.getByRole('dialog')
  const visible = () => dialog.waitFor({ state: 'visible' })
  const hidden = () => dialog.waitFor({ state: 'hidden' })
  const next = () => page.getByRole('button', { name: '下一个亮点', exact: true }).click()
  const bounds = async () => {
    const b = await dialog.evaluate(el => { const r = el.getBoundingClientRect(); return { left: r.left, top: r.top, right: r.right, bottom: r.bottom, width: innerWidth, height: innerHeight } })
    assert.ok(b.left >= 0 && b.top >= 0 && b.right <= b.width + 1 && b.bottom <= b.height + 1, JSON.stringify(b))
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
  }
  try {
    await page.goto(`${base}?fresh&busy`)
    await page.waitForTimeout(1400)
    assert.equal(await dialog.count(), 0)
    await page.evaluate(() => window.onboardingTest.setBusy(false))
    await visible()
    await page.getByRole('heading', { name: '一句话，让故事换个方向' }).waitFor()
    await page.getByRole('button', { name: '复制示例', exact: true }).click()
    assert.match(await page.evaluate(() => window.onboardingTest.copied), /先保留已写正文/)
    await page.getByRole('status').getByText('已复制', { exact: false }).waitFor()
    await bounds()
    await page.screenshot({ path: path.join(output, 'agent-dark.png') })
    await next()
    await page.getByRole('heading', { name: '看清每一次修改，也能撤回' }).waitFor()
    await next()
    await next()
    await page.getByRole('heading', { name: '不急着定稿，先试演三条路' }).waitFor()
    await bounds()
    await page.getByRole('button', { name: '上一步', exact: true }).click()
    await page.getByRole('heading', { name: '先看清这一章为什么要写' }).waitFor()
    await next(); await next()
    await page.getByRole('button', { name: '去配置模型', exact: true }).click()
    await hidden()
    assert.equal(await page.evaluate(() => window.onboardingTest.configured()), true)
    assert.equal(await page.getByRole('textbox').inputValue(), '保留我未发送的创作意图')
    assert.equal(await page.evaluate(() => localStorage.getItem('vela-feature-tour-v1')), 'seen')
    checks.push('Busy writing defers automatic tour; five features, copied example, navigation and settings CTA work without altering the draft message')

    await page.goto(base)
    await page.waitForTimeout(1400)
    assert.equal(await dialog.count(), 0)
    await page.getByRole('button', { name: '功能导览', exact: true }).click()
    await visible()
    await page.keyboard.press('Escape')
    await hidden()
    assert.equal(await page.evaluate(() => document.activeElement?.getAttribute('data-tour')), 'guide-entry')
    await page.getByRole('button', { name: '功能导览', exact: true }).click()
    await visible()
    for (let n = 0; n < 9; n++) {
      await page.keyboard.press('Tab')
      assert.equal(await dialog.evaluate(el => el.contains(document.activeElement)), true)
    }
    await page.getByRole('button', { name: '跳过引导', exact: true }).click()
    await hidden()
    checks.push('Completion survives reload; manual replay, Escape, skip and focus trapping/restoration work')

    for (const theme of ['light', 'dark']) {
      await page.setViewportSize({ width: 390, height: 700 })
      await page.goto(`${base}?fresh&theme=${theme}`)
      await visible()
      await bounds()
      await page.screenshot({ path: path.join(output, `agent-390-${theme}.png`) })
      await page.setViewportSize({ width: 736, height: 420 })
      await bounds()
      await page.getByRole('button', { name: '复制示例', exact: true }).click()
      await next()
      await bounds()
      await page.evaluate(() => document.querySelectorAll('[data-tour]').forEach(el => { if (el.getAttribute('data-tour') !== 'guide-entry') el.removeAttribute('data-tour') }))
      await next()
      await page.waitForFunction(() => !document.querySelector('[data-tour-spotlight]'))
      await bounds()
      await page.screenshot({ path: path.join(output, `missing-targets-${theme}.png`) })
      await page.keyboard.press('Escape')
    }
    checks.push('Light/dark themes, resized windows and missing targets keep the bubble and controls reachable')

    await page.goto(`${base}?fresh`)
    await visible()
    await page.evaluate(() => { window.onboardingTest.copyFailed = true })
    await page.getByRole('button', { name: '复制示例', exact: true }).click()
    await page.getByRole('status').getByText('复制失败', { exact: false }).waitFor()
    await page.getByRole('button', { name: '稍后再看', exact: true }).click()
    await hidden()
    for (const lang of ['en', 'ru']) {
      await page.goto(`${base}?fresh&lang=${lang}`)
      await visible()
      assert.doesNotMatch(await dialog.innerText(), /featureTour\./)
      await bounds()
      await page.keyboard.press('Escape')
    }
    checks.push('Clipboard failure has a manual fallback; English and Russian translations render')
    assert.deepEqual(errors, [])
    fs.writeFileSync(path.join(output, 'results.json'), JSON.stringify({ checks, errors }, null, 2))
    console.log(JSON.stringify({ checks, errors }, null, 2))
  } finally { await browser.close() }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
